import type { ServerDetail } from "../types";

export const magic1: ServerDetail = {
  "slug": "magic-1",
  "title": "Magic: AI UI Component Generator for Developers",
  "metaDescription": "Generate UI components instantly from natural language with Magic! AI-powered tool for Cursor, Windsurf, VSCode & Cline. TypeScript & SVGL support. Try it free!",
  "name": "Magic",
  "author": {
    "name": "21st-dev",
    "href": "https://github.com/21st-dev",
    "avatar": {
      "src": "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-199367026.png",
      "alt": "21st-dev"
    }
  },
  "stars": "5.9k",
  "links": {
    "share": "https://mcpmarket.com/server/magic-1",
    "github": "https://github.com/21st-dev/magic-mcp",
    "npm": "https://www.npmjs.com/package/%4021st-dev/magic"
  },
  "categories": [
    {
      "label": "Developer Tools",
      "href": "/categories/developer-tools"
    },
    {
      "label": "Productivity & Workflow",
      "href": "/categories/productivity-workflow"
    },
    {
      "label": "Design Tools",
      "href": "/categories/design-tools"
    },
    {
      "label": "Official",
      "href": "/categories/official"
    }
  ],
  "description": "Generate modern UI components instantly from natural language descriptions within your IDE.",
  "tabs": {
    "slug": "magic-1",
    "hasReadme": true,
    "longDescription": "Magic empowers developers to create beautiful, modern UI components instantly by using natural language descriptions. It seamlessly integrates with popular IDEs like Cursor, Windsurf, and VSCode (with Cline), providing an AI-powered workflow that streamlines UI development. Access a vast library of pre-built, customizable components inspired by 21st.dev, and see your creations in real-time with full TypeScript and SVGL support. Enhance existing components with advanced features and animations to accelerate your UI development process.",
    "features": [
      "AI-Powered UI Generation from natural language",
      "Multi-IDE Support (Cursor, Windsurf, VSCode)",
      "Access to a modern, customizable component library",
      "Real-time component preview",
      "TypeScript support",
      "AI-Powered UI Generation from natural language descriptions",
      "Multi-IDE Support (Cursor, Windsurf, VSCode + Cline)",
      "Access to a vast collection of pre-built, customizable components",
      "Real-time Preview of generated components",
      "TypeScript Support for type-safe development",
      "AI-Powered UI Generation from natural language",
      "Multi-IDE Support (Cursor, Windsurf, VSCode + Cline)",
      "Access to a vast collection of pre-built, customizable components",
      "Real-time Preview of components as you create them",
      "Full TypeScript and SVGL support"
    ],
    "useCases": [
      "Rapid prototyping of UI components",
      "Generating UI components based on natural language descriptions",
      "Accelerating UI development within supported IDEs",
      "Rapid prototyping of user interfaces",
      "Generating UI components from natural language descriptions",
      "Enhancing existing components with advanced features and animations",
      "Rapid prototyping of UI components",
      "Generating UI elements from natural language descriptions",
      "Enhancing existing UI components with AI-driven features"
    ],
    "faq": [
      {
        "question": "What is Magic and how does it work?",
        "answer": "Magic is an AI-powered tool that generates UI components from natural language descriptions. Simply describe the component you need, and Magic creates it within your IDE (Cursor, Windsurf, VSCode)."
      },
      {
        "question": "Which IDEs does Magic support?",
        "answer": "Magic supports Cursor, Windsurf, and VSCode (via Cline extension). This allows seamless integration into your preferred development environment."
      },
      {
        "question": "Can I customize the components generated by Magic?",
        "answer": "Yes! All generated components are fully customizable. You can modify the styling, functionality, and behavior just like any other component in your codebase."
      },
      {
        "question": "What kind of component library does Magic use?",
        "answer": "Magic provides access to a modern, customizable component library inspired by 21st.dev. This library offers a wide range of pre-built components to accelerate your UI development."
      },
      {
        "question": "Does Magic support TypeScript?",
        "answer": "Yes, Magic offers full TypeScript support, ensuring type-safe development and seamless integration with your TypeScript projects."
      },
      {
        "question": "Does Magic support TypeScript?",
        "answer": "Yes, Magic offers full TypeScript support, ensuring type-safe development for your UI components."
      },
      {
        "question": "How do I install and use Magic?",
        "answer": "You can install Magic using the CLI (recommended) or manually configuring your IDE's MCP config file. Instructions and API key generation are available at 21st.dev/magic/console."
      },
      {
        "question": "Which IDEs does Magic support?",
        "answer": "Magic currently supports Cursor, Windsurf, and VSCode (with the Cline extension). Support for Claude is also available."
      },
      {
        "question": "What is Magic and how does it work?",
        "answer": "Magic is an AI-powered tool that generates UI components from natural language descriptions within your IDE. Simply describe what you need, and Magic builds a polished, customizable component inspired by 21st.dev's library."
      },
      {
        "question": "Are the generated components customizable?",
        "answer": "Yes! All generated components are fully editable and come with well-structured code. You can modify the styling, functionality, and behavior just like any other React component."
      },
      {
        "question": "Which IDEs are supported by Magic?",
        "answer": "Magic currently supports Cursor, Windsurf, and VSCode (with the Cline extension). Support for Claude is also available."
      },
      {
        "question": "What is Magic AI Agent?",
        "answer": "Magic is an AI-powered tool that allows developers to generate UI components instantly by describing them in natural language within your IDE. It supports Cursor, Windsurf, VSCode, and Cline."
      },
      {
        "question": "Can I customize the UI components generated by Magic?",
        "answer": "Yes, all generated components are fully editable and come with well-structured code. You can modify the styling, functionality, and behavior to fit your project's needs."
      },
      {
        "question": "How does Magic integrate with my existing codebase?",
        "answer": "Magic only writes or modifies files related to the components it generates, ensuring seamless integration with your project's code style and structure without affecting other parts of your application."
      },
      {
        "question": "Is Magic free to use?",
        "answer": "Magic Agent is currently in beta, and all features are free during this period. Take advantage of it to see how it can help you build UIs faster!"
      }
    ],
    "mcpTools": [
      {
        "name": "21st_magic_component_builder",
        "description": "\n\"Use this tool when the user requests a new UI component—e.g., mentions /ui, /21 /21st, or asks for a button, input, dialog, table, form, banner, card, or other React component.\nThis tool ONLY returns the text snippet for that UI component. \nAfter calling this tool, you must edit or add files to integrate the snippet into the codebase.\"\n",
        "params": [
          {
            "name": "message",
            "type": "string",
            "required": true,
            "description": "Full users message"
          },
          {
            "name": "searchQuery",
            "type": "string",
            "required": true,
            "description": "Generate a search query for 21st.dev (library for searching UI components) to find a UI component that matches the user's message. Must be a two-four words max or phrase"
          },
          {
            "name": "standaloneRequestQuery",
            "type": "string",
            "required": true,
            "description": "You need to formulate what component user wants to create, based on his message, possbile chat histroy and a place where he makes the request.Extract additional context about what should be done to create a ui component/page based on the user's message, search query, and conversation history, files. Don't halucinate and be on point."
          },
          {
            "name": "absolutePathToCurrentFile",
            "type": "string",
            "required": true,
            "description": "Absolute path to the current file to which we want to apply changes"
          },
          {
            "name": "absolutePathToProjectDirectory",
            "type": "string",
            "required": true,
            "description": "Absolute path to the project root directory"
          }
        ]
      },
      {
        "name": "logo_search",
        "description": "\nSearch and return logos in specified format (JSX, TSX, SVG).\nSupports single and multiple logo searches with category filtering.\nCan return logos in different themes (light/dark) if available.\n\nWhen to use this tool:\n1. When user types \"/logo\" command (e.g., \"/logo GitHub\")\n2. When user asks to add a company logo that's not in the local project\n\nExample queries:\n- Single company: [\"discord\"]\n- Multiple companies: [\"discord\", \"github\", \"slack\"]\n- Specific brand: [\"microsoft office\"]\n- Command style: \"/logo GitHub\" -> [\"github\"]\n- Request style: \"Add Discord logo to the project\" -> [\"discord\"]\n\nFormat options:\n- TSX: Returns TypeScript React component\n- JSX: Returns JavaScript React component\n- SVG: Returns raw SVG markup\n\nEach result includes:\n- Component name (e.g., DiscordIcon)\n- Component code\n- Import instructions\n",
        "params": [
          {
            "name": "format",
            "type": "string",
            "required": true,
            "description": "Output format",
            "enum": [
              "JSX",
              "TSX",
              "SVG"
            ]
          },
          {
            "name": "queries",
            "type": "array",
            "required": true,
            "description": "List of company names to search for logos"
          }
        ]
      },
      {
        "name": "21st_magic_component_inspiration",
        "description": "\n\"Use this tool when the user wants to see component, get inspiration, or /21st fetch data and previews from 21st.dev. This tool returns the JSON data of matching components without generating new code. This tool ONLY returns the text snippet for that UI component. \nAfter calling this tool, you must edit or add files to integrate the snippet into the codebase.\"\n",
        "params": [
          {
            "name": "message",
            "type": "string",
            "required": true,
            "description": "Full users message"
          },
          {
            "name": "searchQuery",
            "type": "string",
            "required": true,
            "description": "Search query for 21st.dev (library for searching UI components) to find a UI component that matches the user's message. Must be a two-four words max or phrase"
          }
        ]
      },
      {
        "name": "21st_magic_component_refiner",
        "description": "\n\"Use this tool when the user requests to re-design/refine/improve current UI component with /ui or /21 commands, \nor when context is about improving, or refining UI for a React component or molecule (NOT for big pages).\nThis tool improves UI of components and returns redesigned version of the component and instructions on how to implement it.\"\n",
        "params": [
          {
            "name": "context",
            "type": "string",
            "required": true,
            "description": "Extract the specific UI elements and aspects that need improvement based on user messages, code, and conversation history. Identify exactly which components (buttons, forms, modals, etc.) the user is referring to and what aspects (styling, layout, responsiveness, etc.) they want to enhance. Do not include generic improvements - focus only on what the user explicitly mentions or what can be reasonably inferred from the available context. If nothing specific is mentioned or you cannot determine what needs improvement, return an empty string."
          },
          {
            "name": "userMessage",
            "type": "string",
            "required": true,
            "description": "Full user's message about UI refinement"
          },
          {
            "name": "absolutePathToRefiningFile",
            "type": "string",
            "required": true,
            "description": "Absolute path to the file that needs to be refined"
          }
        ]
      }
    ]
  },
  "primaryActions": {
    "run": {
      "caption": "One-click cloud hosting",
      "label": "Run on MCP Market",
      "href": "https://app.mcpmarket.com/deploy?name=Magic&npm=%254021st-dev%2Fmagic"
    },
    "tryNowHref": null
  },
  "related": [
    {
      "title": "Related MCPs",
      "more": {
        "label": "View more",
        "href": "/categories/developer-tools"
      },
      "items": [
        {
          "title": "Neon",
          "href": "/server/neon-1",
          "avatar": {
            "src": "/sites/mcpmarket-com-1a9fdbee/server-slug-89dc0d19/avatars/avatar-183852044.png",
            "alt": "neondatabase-labs"
          },
          "description": "Enables natural language interaction with the Neon Management API and databases through the Model Context Protocol."
        },
        {
          "title": "Figma Context",
          "href": "/server/figma-context",
          "avatar": {
            "src": "/sites/mcpmarket-com-1a9fdbee/server-slug-89dc0d19/avatars/avatar-842883.png",
            "alt": "GLips"
          },
          "description": "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol."
        },
        {
          "title": "BrowserTools",
          "href": "/server/browsertools",
          "avatar": {
            "src": "/sites/mcpmarket-com-1a9fdbee/server-slug-89dc0d19/avatars/avatar-194458813.png",
            "alt": "AgentDeskAI"
          },
          "description": "Enables AI-powered applications to monitor and interact with browser data via a Chrome extension and MCP."
        }
      ]
    },
    {
      "title": "Related Skills",
      "more": {
        "label": "View all",
        "href": "/tools/skills"
      },
      "items": [
        {
          "title": "TaskFlow Inbox Triage",
          "href": "/tools/skills/taskflow-inbox-triage-2",
          "avatar": {
            "src": "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png",
            "alt": "openclaw"
          },
          "description": "Automates inbox classification, multi-channel message routing, and asynchronous reply handling using structured task workflows."
        },
        {
          "title": "Meme Maker",
          "href": "/tools/skills/meme-maker-1",
          "avatar": {
            "src": "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png",
            "alt": "openclaw"
          },
          "description": "Searches curated meme templates, suggests ideal joke formats, and renders custom memes in SVG, PNG, or hosted formats."
        },
        {
          "title": "Agent Skill Creator",
          "href": "/tools/skills/agent-skill-creator-1787994711990",
          "avatar": {
            "src": "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png",
            "alt": "openclaw"
          },
          "description": "Authors, repairs, and validates custom AgentSkills and SKILL.md configurations with standardized frontmatter and bundled resources."
        }
      ]
    }
  ]
};
