import type { McpClient } from "./types";

export const MCP_CLIENTS: readonly McpClient[] = [
  {
    slug: "zed",
    name: "Zed",
    metaTitle: "Zed | MCP Clients",
    metaDescription: "Zed is a high-performance code editor built with Rust, offering real-time multiplayer collaboration, cross-platform support (macOS & Linux), and automated license compliance. Download Zed for free!",
    owner: { name: "zed-industries", href: "https://github.com/zed-industries" },
    stars: "91k",
    categories: [
      { label: "Developer Tools", href: "/categories/developer-tools" },
      { label: "Productivity & Workflow", href: "/categories/productivity-workflow" },
      { label: "Collaboration Tools", href: "/categories/collaboration-tools" },
    ],
    description: "Edit code with high performance and multiplayer collaboration.",
    longDescription: "Zed is a high-performance, multiplayer code editor built by the creators of Atom and Tree-sitter. Designed for speed and collaboration, Zed aims to provide a seamless coding experience. It offers features for developing on macOS and Linux, and includes functionalities for running collaboration locally. Contributions are welcome, and the project utilizes cargo-about to manage open-source license compliance.",
    features: ["High-performance code editing", "Multiplayer collaboration", "Built with Rust", "Cross-platform support (macOS and Linux)", "Automated license compliance", "56,279 GitHub stars"],
    useCases: ["Developing applications with high performance requirements", "Real-time collaborative coding", "Code editing with automated license management"],
    faq: [
      { question: "What platforms does Zed support?", answer: "Currently, Zed officially supports macOS and Linux. Windows and web versions are in development." },
      { question: "What is Zed?", answer: "Zed is a high-performance, multiplayer code editor built by the creators of Atom and Tree-sitter. It's designed for speed and real-time collaboration." },
      { question: "What are the main features of Zed?", answer: "Key features include high-performance code editing, real-time multiplayer collaboration, cross-platform support (macOS & Linux), and automated license compliance powered by cargo-about." },
      { question: "Is Zed open source?", answer: "Yes, Zed leverages open source technologies like Rust and includes measures to ensure proper license compliance of its dependencies." },
      { question: "Where can I download Zed?", answer: "You can download Zed directly from the official Zed website or install it via your local package manager on macOS and Linux." },
    ],
    relatedViewMoreHref: "/categories/developer-tools",
    related: [
      { name: "Figma Context", href: "/server/figma-context", description: "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-842883.png", alt: "GLips" } },
      { name: "Magic", href: "/server/magic-1", description: "Generate modern UI components instantly from natural language descriptions within your IDE.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-199367026.png", alt: "21st-dev" } },
      { name: "BrowserTools", href: "/server/browsertools", description: "Enables AI-powered applications to monitor and interact with browser data via a Chrome extension and MCP.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-194458813.png", alt: "AgentDeskAI" } },
    ],
  },
  {
    slug: "cline",
    name: "Cline",
    metaTitle: "Cline | MCP Clients",
    metaDescription: "Automate coding tasks directly in your IDE with Cline! This AI-powered tool creates/edits files, executes commands, uses the browser, and more. Boost your productivity with Cline's intelligent assistance.",
    owner: { name: "cline", href: "https://github.com/cline" },
    stars: "69k",
    categories: [
      { label: "API Development", href: "/categories/api-development" },
      { label: "Developer Tools", href: "/categories/developer-tools" },
      { label: "Productivity & Workflow", href: "/categories/productivity-workflow" },
    ],
    description: "Automates coding tasks directly within your IDE using AI, capable of creating/editing files, executing commands, and using the browser with user permission.",
    longDescription: "Cline is an AI assistant integrated directly into your IDE, enabling autonomous coding capabilities. It leverages the power of AI models to handle complex software development tasks step-by-step, with human-in-the-loop approval for every file change and terminal command. Cline can create and edit files, execute commands in the terminal, use the browser for web development tasks, and even extend its own capabilities through custom tools using the Model Context Protocol (MCP). It supports various API providers and offers features like context addition, checkpoints, and restoration for a safe and efficient coding experience.",
    features: ["Uses a browser for interactive debugging and testing.", "Supports multiple API providers like OpenRouter, Anthropic, and OpenAI.", "Creates and edits files with linter/compiler error monitoring.", "37,114 GitHub stars", "Extends capabilities through custom tools using the Model Context Protocol (MCP).", "Executes commands in the terminal and monitors output."],
    useCases: ["Converting mockups into functional applications.", "Performing end-to-end testing in a browser environment.", "Automating bug fixing using screenshots and error logs."],
    faq: [
      { question: "What tasks can Cline help with?", answer: "Cline can assist with various tasks, including code generation, debugging, testing, fixing linter/compiler errors, and even creating custom tools through the Model Context Protocol (MCP)." },
      { question: "What is Cline?", answer: "Cline is an AI assistant that automates coding tasks directly within your IDE. It can create and edit files, execute commands, use a browser for debugging, and more, all with your approval." },
      { question: "Which API providers does Cline support?", answer: "Cline supports multiple API providers, including OpenRouter, Anthropic, OpenAI, Google Gemini, AWS Bedrock, Azure, GCP Vertex, and any OpenAI-compatible API through LM Studio/Ollama." },
      { question: "Can Cline use a browser?", answer: "Yes, Cline can launch a browser, click elements, type text, and scroll, capturing screenshots and console logs at each step to assist with interactive debugging, end-to-end testing, and general web use." },
      { question: "How does Cline handle file changes and terminal commands?", answer: "Cline provides a human-in-the-loop GUI, requiring your approval for all file changes and terminal commands. This ensures a safe and controlled environment for exploring AI-powered automation." },
    ],
    relatedViewMoreHref: "/categories/api-development",
    related: [
      { name: "Figma Context", href: "/server/figma-context", description: "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-842883.png", alt: "GLips" } },
      { name: "File Modifier", href: "/server/file-modifier", description: "Enables modification of files through a Model Context Protocol server.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-136600825.png", alt: "jpinillagoshawk" } },
      { name: "E2B", href: "/server/e2b", description: "Enables Claude to execute code using E2B sandboxes via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-129434473.png", alt: "e2b-dev" } },
    ],
  },
  {
    slug: "cherry-studio",
    name: "Cherry Studio",
    metaTitle: "Cherry Studio | MCP Clients",
    metaDescription: "Cherry Studio: Access OpenAI, Gemini, Anthropic & more through one desktop client. Build AI assistants, process data, & integrate tools. 22K+ GitHub stars!",
    owner: { name: "CherryHQ", href: "https://github.com/CherryHQ" },
    stars: "52k",
    categories: [
      { label: "Developer Tools", href: "/categories/developer-tools" },
      { label: "Productivity & Workflow", href: "/categories/productivity-workflow" },
      { label: "Collaboration Tools", href: "/categories/collaboration-tools" },
    ],
    description: "Enables users to interact with multiple large language model (LLM) providers through a single desktop client.",
    longDescription: "Cherry Studio is a versatile desktop application designed to streamline interactions with various LLM providers, supporting platforms like OpenAI, Gemini, Anthropic, and local models through Ollama and LM Studio. It offers a range of features including AI assistant creation, multi-model conversations, document processing, and practical tools integration such as AI-powered translation and a global search function. With cross-platform support for Windows, Mac, and Linux, Cherry Studio aims to provide a seamless and efficient user experience for both casual users and developers working with AI models.",
    features: ["Provides practical tools integration, including AI-powered translation and global search.", "Supports multiple LLM providers including OpenAI, Gemini, Anthropic, Ollama, and LM Studio.", "Offers 300+ pre-configured AI assistants and custom assistant creation.", "Enables multi-model simultaneous conversations.", "Supports document and data processing for various formats like Text, Images, Office, and PDF.", "22,105 GitHub stars"],
    useCases: ["Comparing responses from different LLMs for a single query.", "Creating custom AI assistants tailored to specific tasks or domains.", "Managing and processing various document types with AI-powered tools."],
    faq: [
      { question: "Which LLM providers are supported?", answer: "Cherry Studio supports a wide range of LLM providers including OpenAI, Gemini, Anthropic, Ollama, LM Studio, and offers integrations with AI web services like Claude, Perplexity, and Poe." },
      { question: "What can I do with Cherry Studio?", answer: "You can build and use AI assistants, process documents and data, have multi-model conversations, utilize AI-powered translation, perform global searches, and more. It's designed to streamline your AI development workflow." },
      { question: "What is Cherry Studio?", answer: "Cherry Studio is a desktop client that allows you to interact with multiple Large Language Model (LLM) providers like OpenAI, Gemini, and Anthropic from a single interface." },
      { question: "Is Cherry Studio free to use?", answer: "Cherry Studio is free to use, though contributions and sponsorships are welcome to support ongoing development. Individual LLM provider API costs may apply depending on your usage." },
      { question: "What platforms does Cherry Studio support?", answer: "Cherry Studio is cross-platform and available on Windows, Mac, and Linux." },
    ],
    relatedViewMoreHref: "/categories/developer-tools",
    related: [
      { name: "Figma Context", href: "/server/figma-context", description: "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-842883.png", alt: "GLips" } },
      { name: "Magic", href: "/server/magic-1", description: "Generate modern UI components instantly from natural language descriptions within your IDE.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-199367026.png", alt: "21st-dev" } },
      { name: "BrowserTools", href: "/server/browsertools", description: "Enables AI-powered applications to monitor and interact with browser data via a Chrome extension and MCP.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-194458813.png", alt: "AgentDeskAI" } },
    ],
  },
  {
    slug: "librechat",
    name: "LibreChat",
    metaTitle: "LibreChat | MCP Clients",
    metaDescription: "LibreChat is a privacy-focused, self-hosted ChatGPT alternative. Supports multiple AI models, agents, code interpreter, and secure multi-user access. Get started today!",
    owner: { name: "danny-avila", href: "https://github.com/danny-avila" },
    stars: "45k",
    categories: [
      { label: "Developer Tools", href: "/categories/developer-tools" },
      { label: "Other", href: "/categories/other" },
      { label: "Collaboration Tools", href: "/categories/collaboration-tools" },
    ],
    description: "Self-host a privacy-first, versatile ChatGPT alternative supporting multiple AI models and advanced features.",
    longDescription: "LibreChat is an open-source ChatGPT alternative designed for self-hosting, offering users enhanced control and privacy over their AI interactions. It integrates with a wide range of AI models, including OpenAI, Azure, Anthropic, AWS Bedrock, Google, and custom endpoints. Key features include agents with tool integration, multimodal file interactions, code interpreter API, conversation management, and secure multi-user access, all within a customizable and multilingual interface.",
    features: ["Provides multimodal and file interaction capabilities for image and file analysis.", "Features agents with tools integration for advanced AI-driven tasks.", "Enables secure multi-user access with authentication, moderation, and token spend tools.", "23,754 GitHub stars", "Supports multiple AI models including OpenAI, Azure, Anthropic, AWS Bedrock, Google, and custom endpoints.", "Offers a Code Interpreter API for secure, sandboxed code execution."],
    useCases: ["Building custom AI assistants without coding.", "Self-hosting a private and customizable AI chatbot.", "Analyzing images and files with various AI models."],
    faq: [
      { question: "What is LibreChat?", answer: "LibreChat is a self-hosted, open-source chatbot platform that allows you to use multiple AI models like OpenAI, Azure, Anthropic, and more, while maintaining control over your data and privacy." },
      { question: "How do I deploy LibreChat?", answer: "LibreChat can be deployed in various ways, including Docker, Railway, Zeabur, and Sealos, offering flexibility for different environments and technical skill levels. The documentation provides detailed guides for each deployment method." },
      { question: "What AI models does LibreChat support?", answer: "LibreChat supports a wide range of AI models, including OpenAI, Azure OpenAI, Anthropic (Claude), AWS Bedrock, Google (Vertex AI, Gemini), and custom endpoints. It's also compatible with local and remote AI providers like Ollama, groq, and Mistral AI." },
      { question: "Does LibreChat support multi-user access?", answer: "Yes, LibreChat offers secure multi-user access with authentication, moderation tools, and token spend limits. This makes it suitable for teams and organizations that need to collaborate on AI-powered tasks." },
      { question: "What is the Code Interpreter API in LibreChat?", answer: "The Code Interpreter API allows you to securely execute code (Python, Node.js, Go, etc.) within LibreChat in a sandboxed environment. This enables you to process files, run complex calculations, and generate dynamic content, all without compromising your privacy." },
    ],
    relatedViewMoreHref: "/categories/developer-tools",
    related: [
      { name: "Figma Context", href: "/server/figma-context", description: "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-842883.png", alt: "GLips" } },
      { name: "Magic", href: "/server/magic-1", description: "Generate modern UI components instantly from natural language descriptions within your IDE.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-199367026.png", alt: "21st-dev" } },
      { name: "BrowserTools", href: "/server/browsertools", description: "Enables AI-powered applications to monitor and interact with browser data via a Chrome extension and MCP.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-194458813.png", alt: "AgentDeskAI" } },
    ],
  },
  {
    slug: "goose-1",
    name: "Goose",
    metaTitle: "Goose | MCP Clients",
    metaDescription: "Goose is an open-source AI agent that automates complex development tasks. Build projects from scratch, write code, debug, & integrate with APIs. Try Goose today!",
    owner: { name: "block", href: "https://github.com/block" },
    stars: "37k",
    categories: [
      { label: "API Development", href: "/categories/api-development" },
      { label: "Developer Tools", href: "/categories/developer-tools" },
      { label: "Productivity & Workflow", href: "/categories/productivity-workflow" },
    ],
    description: "Automates complex development tasks using an extensible, open-source AI agent.",
    longDescription: "Goose is a local, extensible, open source AI agent designed to automate complex development tasks from start to finish. Going beyond simple code suggestions, Goose can build projects from scratch, write and execute code, debug failures, orchestrate workflows, and interact with external APIs autonomously. It adapts to your workflow, whether you're prototyping, refining code, or managing engineering pipelines, and integrates with any LLM and MCP-enabled APIs.",
    features: ["Automates development tasks", "Works with any LLM", "Can build entire projects from scratch", "Writes and executes code", "Integrates with MCP-enabled APIs", "10,953 GitHub stars"],
    useCases: ["Prototyping new ideas", "Refining existing code", "Managing intricate engineering pipelines"],
    faq: [
      { question: "Is Goose open source?", answer: "Yes, Goose is an extensible, open-source AI agent licensed under Apache 2.0." },
      { question: "Where can I find the Goose documentation?", answer: "You can find the Goose documentation, including quickstart guides, installation instructions, and tutorials, on the official Goose website." },
      { question: "What can Goose do?", answer: "Goose can build projects from scratch, write and execute code, debug failures, orchestrate workflows, and interact with external APIs, all autonomously." },
      { question: "What is Goose?", answer: "Goose is an open-source AI agent that automates complex development tasks, allowing you to build entire projects, write code, and integrate with APIs autonomously." },
      { question: "Is Goose compatible with all LLMs?", answer: "Yes, Goose is designed for maximum flexibility and works with any LLM (Large Language Model)." },
    ],
    relatedViewMoreHref: "/categories/api-development",
    related: [
      { name: "Figma Context", href: "/server/figma-context", description: "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-842883.png", alt: "GLips" } },
      { name: "File Modifier", href: "/server/file-modifier", description: "Enables modification of files through a Model Context Protocol server.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-136600825.png", alt: "jpinillagoshawk" } },
      { name: "E2B", href: "/server/e2b", description: "Enables Claude to execute code using E2B sandboxes via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-129434473.png", alt: "e2b-dev" } },
    ],
  },
  {
    slug: "5ire",
    name: "5ire",
    metaTitle: "5ire | MCP Clients",
    metaDescription: "5ire is a cross-platform AI assistant supporting Model Context Protocol (MCP). Connect to diverse services, local knowledge bases, and enhance your LLM workflows. Featuring prompts library, usage analytics, and more!",
    owner: { name: "nanbingxyz", href: "https://github.com/nanbingxyz" },
    stars: "5.4k",
    categories: [
      { label: "Developer Tools", href: "/categories/developer-tools" },
      { label: "Productivity & Workflow", href: "/categories/productivity-workflow" },
      { label: "Other", href: "/categories/other" },
    ],
    description: "A cross-platform AI assistant and Model Context Protocol (MCP) client that connects to various services and local knowledge bases.",
    longDescription: "5ire is a versatile desktop AI assistant and MCP client designed to streamline interactions with a multitude of AI service providers. It supports local knowledge bases, enabling robust Retrieval-Augmented Generation (RAG) capabilities using integrated multilingual vectorization, and offers seamless integration with tools via Model Context Protocol (MCP) servers. Features include usage analytics, a prompts library, bookmarks, and quick search, all packaged in a sleek, user-friendly interface.",
    features: ["Bookmarks and quick search", "Prompts library", "2,091 GitHub stars", "Supports tools via MCP Servers", "Usage analytics", "Local knowledge base integration"],
    useCases: ["Interacting with databases", "Accessing remote data", "Accessing file systems and system information"],
    faq: [
      { question: "What is 5ire?", answer: "5ire is a cross-platform AI assistant and MCP (Model Context Protocol) client designed to connect to various services and local knowledge bases, enhancing the capabilities of large language models." },
      { question: "What features does 5ire offer?", answer: "5ire includes support for tools via MCP Servers, local knowledge base integration, usage analytics, a prompts library, bookmarks, and quick search functionality to streamline your AI workflows." },
      { question: "What are the prerequisites for activating tools feature?", answer: "Activating the tools feature requires Python, Node.js, and uv (Python package manager) to be installed. Refer to the installation guide for detailed instructions." },
      { question: "What kind of local knowledge bases are supported?", answer: "5ire supports parsing and vectorization of docx, xlsx, pptx, pdf, txt, and csv documents, using the bge-m3 embedding model for robust Retrieval-Augmented Generation (RAG) capabilities." },
      { question: "What is Model Context Protocol (MCP)?", answer: "MCP standardizes how applications provide context to LLMs, similar to how USB-C provides a standard connection for devices. It allows AI models to connect to different data sources and tools." },
    ],
    relatedViewMoreHref: "/categories/developer-tools",
    related: [
      { name: "Figma Context", href: "/server/figma-context", description: "Provides AI coding agents with simplified Figma layout information via the Model Context Protocol.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-842883.png", alt: "GLips" } },
      { name: "Magic", href: "/server/magic-1", description: "Generate modern UI components instantly from natural language descriptions within your IDE.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-199367026.png", alt: "21st-dev" } },
      { name: "BrowserTools", href: "/server/browsertools", description: "Enables AI-powered applications to monitor and interact with browser data via a Chrome extension and MCP.", avatar: { src: "/sites/mcpmarket-com-1a9fdbee/client-slug-53f8082a/avatars/avatar-194458813.png", alt: "AgentDeskAI" } },
    ],
  },
];
