import type { DirectorySection, FaqItem } from "@/components/sites/mcpmarket-com-1a9fdbee/shared/types";

export const DIRECTORY_SECTIONS: readonly DirectorySection[] = [
  {
    title: "Official MCP Servers",
    viewAll: { label: "View all official servers", href: "/categories/official" },
    cards: [
      {
        title: "Firecrawl",
        href: "/server/firecrawl",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-135057108.png", alt: "mendableai" },
        description: "Empowers LLMs with advanced web scraping capabilities for content extraction, crawling, and search functionalities.",
        categories: ["API Development", "Developer Tools"],
        footer: { kind: "stars", value: "4.2k" },
      },
      {
        title: "ElevenLabs",
        href: "/server/elevenlabs-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-94471909.png", alt: "elevenlabs" },
        description: "Enables interaction with Text to Speech and audio processing APIs for MCP clients.",
        categories: ["API Development", "Developer Tools"],
        footer: { kind: "stars", value: "1.5k" },
      },
      {
        title: "Magic",
        href: "/server/magic-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-199367026.png", alt: "21st-dev" },
        description: "Generate modern UI components instantly from natural language descriptions within your IDE.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "stars", value: "5.9k" },
      },
      {
        title: "Browserbase",
        href: "/server/browserbase",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-158221360.png", alt: "browserbase" },
        description: "Enables LLMs to control cloud browsers for web interaction, data extraction, and task automation using Browserbase and Stagehand.",
        categories: ["Developer Tools", "Web Scraping & Data Collection"],
        footer: { kind: "stars", value: "3.4k" },
      },
      {
        title: "Exa",
        href: "/server/exa",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-77906174.png", alt: "exa-labs" },
        description: "Enables AI assistants like Claude to perform web searches using the Exa AI Search API.",
        categories: ["API Development", "Other"],
        footer: { kind: "stars", value: "5.0k" },
      },
      {
        title: "Tavily",
        href: "/server/tavily-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-170207473.png", alt: "tavily-ai" },
        description: "Integrates Tavily's search and data extraction capabilities with AI assistants via the Model Context Protocol.",
        categories: ["Other", "Data Science & ML"],
        footer: { kind: "stars", value: "2.4k" },
      },
    ],
  },
  {
    title: "Featured MCP Servers",
    viewAll: { label: "View all featured servers", href: "/categories/featured" },
    cards: [
      {
        title: "Garmin",
        href: "/server/garmin",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-7362997.png", alt: "Taxuspt" },
        description: "Connects to Garmin Connect and exposes fitness and health data to MCP-compatible clients.",
        categories: ["Other", "Data Science & ML"],
        footer: { kind: "stars", value: "1.2k" },
      },
      {
        title: "FL Studio",
        href: "/server/fl-studio",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-195456457.png", alt: "veenastudio" },
        description: "Connects Claude to FL Studio, enabling AI-driven music creation within the DAW.",
        categories: ["Other", "Data Science & ML"],
        footer: { kind: "stars", value: "105" },
      },
      {
        title: "Blockbench",
        href: "/server/blockbench",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-1903667.png", alt: "jasonjgardner" },
        description: "Integrates a Model Context Protocol server into Blockbench, enabling advanced model interactions.",
        categories: ["Developer Tools", "Other"],
        footer: { kind: "stars", value: "443" },
      },
      {
        title: "CapCut",
        href: "/server/capcut",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-233358203.png", alt: "burnshall-ui" },
        description: "Enables AI agents to directly manipulate CapCut project files via the Model Context Protocol.",
        categories: ["Productivity & Workflow", "Data Science & ML"],
        footer: { kind: "none" },
      },
      {
        title: "Google Search Console",
        href: "/server/google-search-console",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-9718515.png", alt: "ahonn" },
        description: "Provides access to Google Search Console data through the Model Context Protocol.",
        categories: ["Analytics & Monitoring", "Web Scraping & Data Collection"],
        footer: { kind: "stars", value: "273" },
      },
      {
        title: "Yahoo Finance",
        href: "/server/yahoo-finance",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-4680567.png", alt: "narumiruna" },
        description: "Fetches stock data, news, and financial information from Yahoo Finance using an MCP server.",
        categories: ["API Development", "Data Science & ML"],
        footer: { kind: "stars", value: "196" },
      },
    ],
  },
  {
    title: "Top MCP Servers",
    viewAll: { label: "View leaderboard", href: "/leaderboards" },
    cards: [
      {
        title: "Superpowers",
        href: "/server/superpowers",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-45416.png", alt: "obra" },
        description: "Empowers AI coding agents with a comprehensive and structured software development workflow, from design refinement to TDD-driven implementation.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "stars", value: "290k" },
      },
      {
        title: "World Monitor",
        href: "/server/world-monitor",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-996596.png", alt: "koala73" },
        description: "Provides real-time global intelligence through AI-powered news aggregation, geopolitical monitoring, and infrastructure tracking in a unified situational awareness interface.",
        categories: ["Data Science & ML", "Analytics & Monitoring"],
        footer: { kind: "stars", value: "87k" },
      },
      {
        title: "Ruflo",
        href: "/server/ruflo",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-2934394.png", alt: "ruvnet" },
        description: "Orchestrates intelligent multi-agent swarms for Claude, coordinating autonomous workflows and building conversational AI systems.",
        categories: ["Developer Tools", "Data Science & ML"],
        footer: { kind: "stars", value: "73k" },
      },
      {
        title: "OpenSpec",
        href: "/server/openspec",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-203414896.png", alt: "Fission-AI" },
        description: "Facilitates spec-driven development to ensure alignment between humans and AI coding assistants before any code is written.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "stars", value: "70k" },
      },
      {
        title: "TrendRadar",
        href: "/server/trendradar",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-77180927.png", alt: "sansan0" },
        description: "Aggregates trending topics from over 35 platforms, offering intelligent filtering, automated multi-channel notifications, and AI-powered conversational analysis for deep news insights.",
        categories: ["Data Science & ML", "Analytics & Monitoring"],
        footer: { kind: "stars", value: "62k" },
      },
      {
        title: "Context7",
        href: "/server/context7-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-74989412.png", alt: "upstash" },
        description: "Fetches up-to-date documentation and code examples for LLMs and AI code editors directly from the source.",
        categories: ["API Development", "Developer Tools"],
        footer: { kind: "stars", value: "62k" },
      },
    ],
  },
  {
    title: "Latest MCP Servers",
    viewAll: { label: "View all new servers", href: "/server" },
    cards: [
      {
        title: "NotchMate",
        href: "/server/notchmate",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-66392959.png", alt: "aleksandr-developer1" },
        description: "Transforms the MacBook notch area into an interactive companion displaying music, notes, calendar, Jira, calls, and AI interactions.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "none" },
      },
      {
        title: "Lovely Composer",
        href: "/server/lovely-composer",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-300064382.png", alt: "baichuan4167-lang" },
        description: "Enables AI agents to compose chiptune music in Lovely Composer by directly manipulating its project files.",
        categories: ["Developer Tools", "Data Science & ML"],
        footer: { kind: "none" },
      },
      {
        title: "Atlias",
        href: "/server/atlias",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-320328985.png", alt: "ridelink0" },
        description: "Provides a sub-harness that enhances large language models like Claude Code, Codex, Antigravity, and Gemini CLI with shared memory, knowledge graphs, and robust safety features.",
        categories: ["Developer Tools", "Data Science & ML"],
        footer: { kind: "zero" },
      },
      {
        title: "Research Dossier",
        href: "/server/research-dossier",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-34187062.png", alt: "BhawanjitSinghSaini" },
        description: "Decompose complex research briefs, synthesize findings into structured, cited dossiers, and export them for client delivery.",
        categories: ["Productivity & Workflow", "Web Scraping & Data Collection"],
        footer: { kind: "zero" },
      },
      {
        title: "Agent Safe Tools",
        href: "/server/agent-safe-tools",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-276247618.png", alt: "wangke-112" },
        description: "Empower AI coding agents to safely search production logs and inspect databases using natural language commands.",
        categories: ["Database Management", "Developer Tools"],
        footer: { kind: "none" },
      },
      {
        title: "Cal",
        href: "/server/cal-2",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-272030991.png", alt: "Caloptreyx" },
        description: "Enables AI assistants to manage your Calagopus Panel through its API, respecting defined permissions.",
        categories: ["API Development", "Developer Tools"],
        footer: { kind: "zero" },
      },
    ],
  },
  {
    title: "MCP Clients",
    viewAll: { label: "View all clients", href: "/client" },
    cards: [
      {
        title: "Zed",
        href: "/client/zed",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-79345384.png", alt: "zed-industries" },
        description: "Edit code with high performance and multiplayer collaboration.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "stars", value: "91k" },
      },
      {
        title: "Cline",
        href: "/client/cline",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-184127137.png", alt: "cline" },
        description: "Automates coding tasks directly within your IDE using AI, capable of creating/editing files, executing commands, and using the browser with user permission.",
        categories: ["API Development", "Developer Tools"],
        footer: { kind: "stars", value: "69k" },
      },
      {
        title: "Cherry Studio",
        href: "/client/cherry-studio",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-187777663.png", alt: "CherryHQ" },
        description: "Enables users to interact with multiple large language model (LLM) providers through a single desktop client.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "stars", value: "52k" },
      },
      {
        title: "LibreChat",
        href: "/client/librechat",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-110412045.png", alt: "danny-avila" },
        description: "Self-host a privacy-first, versatile ChatGPT alternative supporting multiple AI models and advanced features.",
        categories: ["Developer Tools", "Other"],
        footer: { kind: "stars", value: "45k" },
      },
      {
        title: "Goose",
        href: "/client/goose-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-185116535.png", alt: "block" },
        description: "Automates complex development tasks using an extensible, open-source AI agent.",
        categories: ["API Development", "Developer Tools"],
        footer: { kind: "stars", value: "37k" },
      },
      {
        title: "5ire",
        href: "/client/5ire",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-11755645.png", alt: "nanbingxyz" },
        description: "A cross-platform AI assistant and Model Context Protocol (MCP) client that connects to various services and local knowledge bases.",
        categories: ["Developer Tools", "Productivity & Workflow"],
        footer: { kind: "stars", value: "5.4k" },
      },
    ],
  },
  {
    title: "Top Agent Skills",
    badge: { label: "What are Agent Skills?", href: "/tools/skills/what-are-skills" },
    viewAll: { label: "View all skills", href: "/tools/skills" },
    cards: [
      {
        title: "Meme Maker",
        href: "/tools/skills/meme-maker-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png", alt: "openclaw" },
        description: "Searches curated meme templates, suggests ideal joke formats, and renders custom memes in SVG, PNG, or hosted formats.",
        categories: ["Content Management"],
        footer: { kind: "stars", value: "388k" },
      },
      {
        title: "Agent Skill Creator",
        href: "/tools/skills/agent-skill-creator-1787994711990",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png", alt: "openclaw" },
        description: "Authors, repairs, and validates custom AgentSkills and SKILL.md configurations with standardized frontmatter and bundled resources.",
        categories: ["Productivity & Workflow"],
        footer: { kind: "stars", value: "388k" },
      },
      {
        title: "Sherpa ONNX Local Text-to-Speech",
        href: "/tools/skills/sherpa-onnx-local-text-to-speech",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png", alt: "openclaw" },
        description: "Generates natural speech audio locally and offline using the high-performance sherpa-onnx runtime and ONNX voice models.",
        categories: ["Data Science & ML"],
        footer: { kind: "stars", value: "388k" },
      },
      {
        title: "OpenClaw Channel Configurator",
        href: "/tools/skills/openclaw-channel-configurator",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png", alt: "openclaw" },
        description: "Configures, repairs, and verifies chat messaging channels securely using non-interactive CLI commands and secret references.",
        categories: ["Collaboration Tools"],
        footer: { kind: "stars", value: "388k" },
      },
      {
        title: "1Password CLI",
        href: "/tools/skills/1password-cli-1",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png", alt: "openclaw" },
        description: "Integrates 1Password CLI to securely authenticate, manage vaults, and inject environment secrets without leaking credentials into chat or logs.",
        categories: ["Security & Testing"],
        footer: { kind: "stars", value: "388k" },
      },
      {
        title: "Background Coding Agent",
        href: "/tools/skills/background-coding-agent",
        avatar: { src: "/sites/mcpmarket-com-1a9fdbee/root-8a5edab2/avatars/avatar-252820863.png", alt: "openclaw" },
        description: "Delegates complex coding tasks, refactors, and issue-to-PR workflows to autonomous background CLI workers including Claude Code, Codex, and OpenCode.",
        categories: ["Productivity & Workflow"],
        footer: { kind: "stars", value: "388k" },
      },
    ],
  },
];

export const FAQ_ITEMS: readonly FaqItem[] = [
  { question: "What is MCP (Model Context Protocol)?", answer: "MCP (Model Context Protocol) is an open-source standard created by Anthropic that enables AI applications like Claude and ChatGPT to connect to external tools, data sources, and services. Think of it like a USB-C port for AI—a universal connector that lets AI models plug into various tools and databases in a consistent, standardized way." },
  { question: "How does MCP work?", answer: "MCP works through three main components: MCP Hosts (AI applications like Claude Desktop), MCP Clients (connectors within the host that communicate with servers), and MCP Servers (external services that provide data and tools). When you ask an AI to perform a task requiring external data, the client discovers available tools, sends requests to the appropriate server, and returns results to the AI." },
  { question: "What can MCP servers do?", answer: "MCP servers can connect AI to virtually any external system. Common capabilities include: accessing databases and file systems, integrating with tools like GitHub, Slack, and Notion, executing code and running tests, managing cloud infrastructure, scraping web data, and automating workflows. Each server exposes specific tools the AI can use during conversations." },
  { question: "Who uses MCP?", answer: "MCP is used by developers, enterprises, and AI enthusiasts who want to extend AI capabilities. Major AI providers including OpenAI, Google DeepMind, and Anthropic support MCP. It's particularly popular among developers building AI agents, companies creating enterprise knowledge assistants, and teams automating complex workflows." },
  { question: "How do I install an MCP server?", answer: "MCP servers can be installed in AI applications like Claude Desktop or Cursor. Typically, you add the server configuration to your app's settings file (like claude_desktop_config.json), specifying the server command and any required environment variables. Many servers are available via npm or can be run directly from their GitHub repositories." },
  { question: "Is MCP secure?", answer: "MCP includes built-in security features like authentication specs and permission controls. However, as with any integration, you should review server code before installation, use environment variables for sensitive credentials, only install servers from trusted sources, and follow the principle of least privilege when granting permissions." },
  { question: "What's the difference between MCP and regular APIs?", answer: "While MCP uses APIs under the hood, it's specifically designed for AI context. Regular APIs serve general web applications, while MCP provides a standardized interface that AI models can discover and use autonomously. MCP servers are tool-agnostic, schema-driven, and reusable across different AI agents without custom integration code." },
  { question: "Can I build my own MCP server?", answer: "Yes! MCP provides SDKs in TypeScript, Python, C#, Java, and other languages to help you build custom servers. You can create servers that expose your own tools, connect to proprietary systems, or wrap existing APIs in an MCP-compatible interface. The official documentation provides guides and examples to get started." },
];
