import type { Listing } from "../lib/types.ts";

export const LISTINGS: readonly Listing[] = [
  {
    slug: "frameboard",
    name: "Frameboard",
    summary: "Lay out storyboards and shot lists for short videos.",
    category: "video",
    tags: ["storyboard", "planning"],
    stars: "4.2k",
    author: { label: "Frameboard Labs", href: "https://example.com/frameboard" },
    about: [
      "Frameboard is a demo listing used to show how a directory entry reads.",
      "Lay out storyboards and shot lists for short videos. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "clipcaption",
    name: "Clipcaption",
    summary: "Generate and style captions for talking-head clips.",
    category: "video",
    tags: ["captions", "subtitles"],
    stars: "2.8k",
    author: { label: "Clipcaption Studio", href: "https://example.com/clipcaption" },
    about: [
      "Clipcaption is a demo listing used to show how a directory entry reads.",
      "Generate and style captions for talking-head clips. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "pixelpalette",
    name: "Pixelpalette",
    summary: "Build accessible color palettes from a single brand color.",
    category: "design",
    tags: ["color", "accessibility"],
    stars: "6.1k",
    author: { label: "Pixelpalette Co", href: "https://example.com/pixelpalette" },
    about: [
      "Pixelpalette is a demo listing used to show how a directory entry reads.",
      "Build accessible color palettes from a single brand color. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "gridwright",
    name: "Gridwright",
    summary: "Design responsive layout grids and export them as CSS.",
    category: "design",
    tags: ["layout", "css"],
    stars: "3.4k",
    author: { label: "Gridwright Works", href: "https://example.com/gridwright" },
    about: [
      "Gridwright is a demo listing used to show how a directory entry reads.",
      "Design responsive layout grids and export them as CSS. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "taskloom",
    name: "Taskloom",
    summary: "Turn meeting notes into a prioritised task list.",
    category: "productivity",
    tags: ["tasks", "notes"],
    stars: "5.5k",
    author: { label: "Taskloom Inc", href: "https://example.com/taskloom" },
    about: [
      "Taskloom is a demo listing used to show how a directory entry reads.",
      "Turn meeting notes into a prioritised task list. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "dayfold",
    name: "Dayfold",
    summary: "Plan your week in focused blocks and track what slipped.",
    category: "productivity",
    tags: ["calendar", "focus"],
    stars: "1.9k",
    author: { label: "Dayfold Team", href: "https://example.com/dayfold" },
    about: [
      "Dayfold is a demo listing used to show how a directory entry reads.",
      "Plan your week in focused blocks and track what slipped. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "patchbay",
    name: "Patchbay",
    summary: "Review pull requests with inline summaries and risk notes.",
    category: "developer-tools",
    tags: ["review", "git"],
    stars: "12.4k",
    author: { label: "Patchbay Dev", href: "https://example.com/patchbay" },
    about: [
      "Patchbay is a demo listing used to show how a directory entry reads.",
      "Review pull requests with inline summaries and risk notes. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "testwren",
    name: "Testwren",
    summary: "Generate unit tests for untested functions in minutes.",
    category: "developer-tools",
    tags: ["testing", "automation"],
    stars: "8.7k",
    author: { label: "Testwren Labs", href: "https://example.com/testwren" },
    about: [
      "Testwren is a demo listing used to show how a directory entry reads.",
      "Generate unit tests for untested functions in minutes. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "metricnest",
    name: "Metricnest",
    summary: "Dashboards for product metrics without a data team.",
    category: "analytics",
    tags: ["dashboards", "metrics"],
    stars: "3.9k",
    author: { label: "Metricnest Analytics", href: "https://example.com/metricnest" },
    about: [
      "Metricnest is a demo listing used to show how a directory entry reads.",
      "Dashboards for product metrics without a data team. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "funnelscope",
    name: "Funnelscope",
    summary: "Spot where visitors drop out of your signup funnel.",
    category: "analytics",
    tags: ["funnel", "conversion"],
    stars: "2.2k",
    author: { label: "Funnelscope Ltd", href: "https://example.com/funnelscope" },
    about: [
      "Funnelscope is a demo listing used to show how a directory entry reads.",
      "Spot where visitors drop out of your signup funnel. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "campaignkite",
    name: "Campaignkite",
    summary: "Draft, schedule and review email campaigns in one place.",
    category: "marketing",
    tags: ["email", "campaigns"],
    stars: "4.6k",
    author: { label: "Campaignkite Media", href: "https://example.com/campaignkite" },
    about: [
      "Campaignkite is a demo listing used to show how a directory entry reads.",
      "Draft, schedule and review email campaigns in one place. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "postharbor",
    name: "Postharbor",
    summary: "Plan social posts around one calendar and one voice.",
    category: "marketing",
    tags: ["social", "scheduling"],
    stars: "1.3k",
    author: { label: "Postharbor Studio", href: "https://example.com/postharbor" },
    about: [
      "Postharbor is a demo listing used to show how a directory entry reads.",
      "Plan social posts around one calendar and one voice. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "reelsmith",
    name: "Reelsmith",
    summary: "Cut long recordings into short vertical clips.",
    category: "video",
    tags: ["clips", "editing"],
    stars: "3.1k",
    author: { label: "Reelsmith Labs", href: "https://example.com/reelsmith" },
    about: [
      "Reelsmith is a demo listing used to show how a directory entry reads.",
      "Cut long recordings into short vertical clips. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "soundstage",
    name: "Soundstage",
    summary: "Clean up voice tracks and balance levels automatically.",
    category: "video",
    tags: ["audio", "editing"],
    stars: "2.4k",
    author: { label: "Soundstage Audio", href: "https://example.com/soundstage" },
    about: [
      "Soundstage is a demo listing used to show how a directory entry reads.",
      "Clean up voice tracks and balance levels automatically. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "thumbcraft",
    name: "Thumbcraft",
    summary: "Design video thumbnails from reusable templates.",
    category: "video",
    tags: ["thumbnails", "templates"],
    stars: "1.7k",
    author: { label: "Thumbcraft Co", href: "https://example.com/thumbcraft" },
    about: [
      "Thumbcraft is a demo listing used to show how a directory entry reads.",
      "Design video thumbnails from reusable templates. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "castlight",
    name: "Castlight",
    summary: "Schedule and publish videos to every channel at once.",
    category: "video",
    tags: ["publishing", "scheduling"],
    stars: "2.0k",
    author: { label: "Castlight Media", href: "https://example.com/castlight" },
    about: [
      "Castlight is a demo listing used to show how a directory entry reads.",
      "Schedule and publish videos to every channel at once. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "lintfox",
    name: "Lintfox",
    summary: "Fast linting with fixes explained in plain language.",
    category: "developer-tools",
    tags: ["lint", "quality"],
    stars: "9.3k",
    author: { label: "Lintfox Dev", href: "https://example.com/lintfox" },
    about: [
      "Lintfox is a demo listing used to show how a directory entry reads.",
      "Fast linting with fixes explained in plain language. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "shipwell",
    name: "Shipwell",
    summary: "One-command releases with changelogs and rollbacks.",
    category: "developer-tools",
    tags: ["release", "ci"],
    stars: "7.2k",
    author: { label: "Shipwell Inc", href: "https://example.com/shipwell" },
    about: [
      "Shipwell is a demo listing used to show how a directory entry reads.",
      "One-command releases with changelogs and rollbacks. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "schemaleaf",
    name: "Schemaleaf",
    summary: "Visualise database schemas and generate migrations.",
    category: "developer-tools",
    tags: ["database", "migrations"],
    stars: "5.8k",
    author: { label: "Schemaleaf Works", href: "https://example.com/schemaleaf" },
    about: [
      "Schemaleaf is a demo listing used to show how a directory entry reads.",
      "Visualise database schemas and generate migrations. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
  {
    slug: "logbloom",
    name: "Logbloom",
    summary: "Search and group application logs without setup.",
    category: "developer-tools",
    tags: ["logs", "debugging"],
    stars: "4.4k",
    author: { label: "Logbloom Labs", href: "https://example.com/logbloom" },
    about: [
      "Logbloom is a demo listing used to show how a directory entry reads.",
      "Search and group application logs without setup. Replace this text with your own listing copy.",
    ],
    features: ["Quick setup", "Clear defaults", "Export your work"],
    useCases: ["Trying the template", "Seeing a full detail page"],
    faq: [{ question: "Is there a free plan?", answer: "Yes, this demo listing is free to try." }],
  },
];
